---

- name: pull the latest aadl/cups
  docker_image:
    name: aadl/cups-alpine:{{cups_image_version}}

- name: copy cups config directory
  synchronize: src=cups-config/ dest={{cups_config_directory}}

- name: copy ppd file for downtown-pub-1 printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/downtown-pub-1.ppd"
- name: copy ppd file for downtown-pub-2 printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/downtown-pub-2.ppd"
- name: copy ppd file for downtown-pub-3 printer
  copy:
    src: ppds/Lexmark_X463de.ppd
    dest: "{{ cups_config_directory }}/ppd/downtown-pub-3.ppd"
- name: copy ppd file for mcb-pub-1 printer
  copy:
    src: ppds/Lexmark_XM1100_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/mcb-pub-1.ppd"
- name: copy ppd file for mcb-pub-2 printer
  copy:
    src: ppds/Lexmark_XM1100_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/mcb-pub-2.ppd"
- name: copy ppd file for pitts-pub-1 printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/pitts-pub-1.ppd"
- name: copy ppd file for pitts-pub-2 printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/pitts-pub-2.ppd"
- name: copy ppd file for trav-copier printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/trav-copier.ppd"
- name: copy ppd file for trav-pub printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/trav-pub.ppd"
- name: copy ppd file for trav-staff printer
  copy:
    src: ppds/Lexmark_MX510_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/trav-staff.ppd"
- name: copy ppd files for west-pub-1 printer
  copy:
    src: ppds/Lexmark_XM1100_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/west-pub-1.ppd"
- name: copy ppd file for west-pub-2 printer
  copy:
    src: ppds/Lexmark_XM1100_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/west-pub-2.ppd"
- name: copy ppd file for west-staff-front printer
  copy:
    src: ppds/Lexmark_XM1100_Series.ppd
    dest: "{{ cups_config_directory }}/ppd/west-staff-front.ppd"
- name: Start cups server
  docker_container:
    name: cups-server
    image: aadl/cups-alpine:{{cups_image_version}}
    published_ports:
      - "{{ cups_access_port }}:631/tcp"
    env:
        CUPS_USER_ADMIN={{cups_admin_user}}
        CUPS_USER_PASSWORD={{cups_admin_password}}
    volumes:
      - "{{ cups_config_directory }}:/etc/cups"
      - "{{ cups_pdf_spool_directory }}:/var/spool/cups-pdf"
